"""update table

Revision ID: 8a60d1010a1a
Revises: f3bbabf6a036
Create Date: 2023-05-17 11:34:55.542149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a60d1010a1a'
down_revision = 'f3bbabf6a036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fitness_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fitness_programs', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
