"""create tables

Revision ID: f3bbabf6a036
Revises: 
Create Date: 2023-05-10 18:19:11.429591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bbabf6a036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('gym_frequency', sa.String(length=50), nullable=False),
    sa.Column('training_split', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_fitness_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fitness_program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitness_program_id'], ['fitness_programs.id'], name=op.f('fk_user_fitness_programs_fitness_program_id_fitness_programs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_fitness_programs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fitness_programs')
    op.drop_table('users')
    op.drop_table('fitness_programs')
    # ### end Alembic commands ###
